### PR TITLE
Several improvements and cleanups of the code and others.

### PR DESCRIPTION
**Pull request by 0rangeFox**
Hey, here are some improvements I have already made, and I hope you like them.

### CODE REVIEW

**Comment by BrianGrug** [comment]
Thank you! I'll review it when I'm home!

**Review by InvisRaidinq — COMMENTED** [review]
Changes look good from a quick glance - has this been tested in a development environment yet?

**Comment by 0rangeFox** [comment]
It hasn't been tested yet, but I would like you to do it yourselves, because I don't have those tools right now.

**Comment by BrianGrug** [comment]
Hey I have one more commit to push then me and Invis will finish reviewing it!

**Comment by 0rangeFox** [comment]
Ok, so push that commit and I'll implement that code right away or improve it if necessary.

**Comment by BrianGrug** [comment]
Sounds good, just pushed. The only thing I can really say is just try to make use of Lombok!

**Comment by 0rangeFox** [comment]
You pushed to another branch, are you not mistaken?

**Comment by BrianGrug** [comment]
Sorry, just merged it

**Comment by 0rangeFox** [comment]
There, I think it's all straight and now just give it a review.

**Comment by BrianGrug** [comment]
Just waiting for @InvisRaidinq to review too!

**Review by InvisRaidinq — APPROVED** [review]
I'm happy with all changes up to here, I think we test it and then if it still functions as expected we merge.

**Pull request closed without merging**
